test

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -54,79 +54,79 @@ jobs:
       if: success()
       run: docker push ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
     
-      
-  test:
-    runs-on: robot-dind
-    needs: build
-    permissions:
-      contents: read
-      packages: write
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
 
-    - name: Login to GitHub Container Registry
-      uses: docker/login-action@v2
-      with:
-        registry: ghcr.io
-        username: '${{ github.repository_owner }}'
-        password: '${{ secrets.GITHUB_TOKEN }}'
+  # test:
+  #   runs-on: robot-dind
+  #   needs: build
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v3
 
-    - name: Downcase REPO
-      run: |
-        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+  #   - name: Login to GitHub Container Registry
+  #     uses: docker/login-action@v2
+  #     with:
+  #       registry: ghcr.io
+  #       username: '${{ github.repository_owner }}'
+  #       password: '${{ secrets.GITHUB_TOKEN }}'
 
-    - name: Pull Docker image
-      run: docker pull ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
+  #   - name: Downcase REPO
+  #     run: |
+  #       echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
-    - name: Run bngblaster app
-      run: |
-        docker run -d --name bngblaster-container -p 8505:8505 ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
+  #   - name: Pull Docker image
+  #     run: docker pull ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
 
-    - name: Wait and check container status
-      run: |
-        sleep 10
-        STATUS=$(docker inspect --format='{{.State.Status}}' bngblaster-container)
-        echo "Container status: $STATUS"
-        if [ "$STATUS" = "running" ]; then
-          echo "Container is running!"
-        else
-          echo "Container is not running: $STATUS"
-          exit 1
-        fi
+  #   - name: Run bngblaster app
+  #     run: |
+  #       docker run -d --name bngblaster-container -p 8505:8505 ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
 
-    - name: Run Robot Framework tests
-      run: robot tests/
+  #   - name: Wait and check container status
+  #     run: |
+  #       sleep 10
+  #       STATUS=$(docker inspect --format='{{.State.Status}}' bngblaster-container)
+  #       echo "Container status: $STATUS"
+  #       if [ "$STATUS" = "running" ]; then
+  #         echo "Container is running!"
+  #       else
+  #         echo "Container is not running: $STATUS"
+  #         exit 1
+  #       fi
 
-    - name: Delete image if test fail
-      if: failure()
-      run: |
-        REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
-        echo "Repo name: $REPO_NAME"
+  #   - name: Run Robot Framework tests
+  #     run: robot tests/
 
-        VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-        "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" \
-        | jq -r '.[] | select(.metadata.container.tags[] == "v1.${{ github.run_number }}") | .id')
+  #   - name: Delete image if test fail
+  #     if: failure()
+  #     run: |
+  #       REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
+  #       echo "Repo name: $REPO_NAME"
 
-        echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV
-        echo "Package version ID: $VERSION_ID"
+  #       VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+  #       "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" \
+  #       | jq -r '.[] | select(.metadata.container.tags[] == "v1.${{ github.run_number }}") | .id')
 
-        curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
+  #       echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV
+  #       echo "Package version ID: $VERSION_ID"
 
-    - name: Tag latest image and push to GitHub Container Registry
-      if: success()
-      run: |
-        docker tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} ghcr.io/${{ env.REPO }}:latest
-        docker push ghcr.io/${{ env.REPO }}:latest
+  #       curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+  #       -H "Accept: application/vnd.github.v3+json" \
+  #       "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
+
+  #   - name: Tag latest image and push to GitHub Container Registry
+  #     if: success()
+  #     run: |
+  #       docker tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} ghcr.io/${{ env.REPO }}:latest
+  #       docker push ghcr.io/${{ env.REPO }}:latest
         
-    - name: 'Upload robot test result'
-      if: always()
-      uses: actions/upload-artifact@v4.6.0
-      with:
-        name: robot-test-report
-        path: ./report.html
+  #   - name: 'Upload robot test result'
+  #     if: always()
+  #     uses: actions/upload-artifact@v4.6.0
+  #     with:
+  #       name: robot-test-report
+  #       path: ./report.html
 
 
   # update: 
