test: save cache to local

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -25,18 +25,51 @@ jobs:
         username: '${{ github.repository_owner }}'
         password: '${{ secrets.GITHUB_TOKEN }}'
 
+    - name: Cache Docker layers
+      uses: actions/cache@v4
+      with:
+        path: /tmp/.buildx-cache
+        key: ${{ runner.os }}-buildx-${{ github.sha }}
+        restore-keys: |
+          ${{ runner.os }}-buildx-
+
     - name: Downcase REPO
       run: |
         echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
-      
+
+    - name: Build image
+      run: |
+        docker buildx build \
+          --cache-from=type=local,src=/tmp/.buildx-cache \
+          --load \
+          --tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} .
+
+    - name: Run bngblaster app
+      run: |
+        docker run -d --name bngblaster-container -p 8505:8505 ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
+        sleep 15
+
+    - name: Check container status
+      run: |
+        docker ps -a
+        docker images
+        STATUS=$(docker inspect --format='{{.State.Status}}' bngblaster-container)
+        echo "Container status: $STATUS"
+        if [ "$STATUS" != "running" ]; then
+          echo "Container failed to start!"
+          docker logs bngblaster-container
+          exit 1
+        fi
+        echo "Container is running successfully!"
+        
     - name: Build and push image to ghcr.io
       run: |
         docker buildx build \
-          --cache-from=type=registry,ref=ghcr.io/${{ env.REPO }}:cache \
-          --cache-to=type=registry,ref=ghcr.io/${{ env.REPO }}:cache,mode=max \
+          --cache-from=type=local,src=/tmp/.buildx-cache \
+          --cache-to=type=local,dest=/tmp/.buildx-cache \
           --push \
           --tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} . 
 
