test: echo vars

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -6,142 +6,117 @@ on:
       - main
   pull_request:
     branches:
-      - main
-  workflow_dispatch:
-    inputs:
-      job_name:
-        description: 'Choose only job to re-run'
-        required: true
-        type: choice
-        options:
-          - build
-          - test
-          - update
-      privious_run_number:
-        description: 'Enter previous run number (leave empty for new run)'
-        required: false
-        type: number
-        
-env:
-  RUN_NUMBER: ${{ inputs.privious_run_number || github.run_number }}
+      - main  
 
 jobs:
   build:
-    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job_name == 'build') }}
     runs-on: robot-dind
     permissions:
       contents: read
       packages: write
     steps:
+    # - name: Checkout code
+    #   uses: actions/checkout@v3
 
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Login to GitHub Container Registry
-      uses: docker/login-action@v2
-      with:
-        registry: ghcr.io
-        username: '${{ github.repository_owner }}'
-        password: '${{ secrets.GITHUB_TOKEN }}'
+    # - name: Login to GitHub Container Registry
+    #   uses: docker/login-action@v2
+    #   with:
+    #     registry: ghcr.io
+    #     username: '${{ github.repository_owner }}'
+    #     password: '${{ secrets.GITHUB_TOKEN }}'
 
     - name: Downcase REPO
       run: |
         echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+    - name: Echo vars
+      run: |
+        echo ${{ github.repository_owner}}
+        echo ${{ env.REPO}}
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+  #   - name: Set up Docker Buildx
+  #     uses: docker/setup-buildx-action@v3
       
-    - name: Build and push image to ghcr.io
-      run: |
-        docker buildx build \
-          --cache-from=type=registry,ref=ghcr.io/${{ env.REPO }}:cache \
-          --cache-to=type=registry,ref=ghcr.io/${{ env.REPO }}:cache,mode=max \
-          --push \
-          --tag ghcr.io/${{ env.REPO }}:v1.${{ github.RUN_NUMBER }} . 
+  #   - name: Build and push image to ghcr.io
+  #     run: |
+  #       docker buildx build \
+  #         --cache-from=type=registry,ref=ghcr.io/${{ env.REPO }}:cache \
+  #         --cache-to=type=registry,ref=ghcr.io/${{ env.REPO }}:cache,mode=max \
+  #         --push \
+  #         --tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} . 
 
-  test:
-    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job_name == 'test') }}
-    runs-on: robot-dind
-    needs: build
-    permissions:
-      contents: read
-      packages: write
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+  # test:
+  #   runs-on: robot-dind
+  #   needs: build
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+    # - name: Checkout code
+    #   uses: actions/checkout@v3
 
-    - name: Login to GitHub Container Registry
-      uses: docker/login-action@v2
-      with:
-        registry: ghcr.io
-        username: '${{ github.repository_owner }}'
-        password: '${{ secrets.GITHUB_TOKEN }}'
+    # - name: Login to GitHub Container Registry
+    #   uses: docker/login-action@v2
+    #   with:
+    #     registry: ghcr.io
+    #     username: '${{ github.repository_owner }}'
+    #     password: '${{ secrets.GITHUB_TOKEN }}'
 
-    - name: Downcase REPO
-      run: |
-        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+    # - name: Downcase REPO
+    #   run: |
+    #     echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
-    - name: Pull Docker image
-      run: docker pull ghcr.io/${{ env.REPO }}:v1.${{ github.RUN_NUMBER }}
+    # - name: Pull Docker image
+    #   run: docker pull ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
 
-    - name: Run bngblaster app
-      run: |
-        docker run -d --name bngblaster-container -p 8505:8505 ghcr.io/${{ env.REPO }}:v1.${{ github.RUN_NUMBER }}
+    # - name: Run bngblaster app
+    #   run: |
+    #     docker run -d --name bngblaster-container -p 8505:8505 ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }}
 
-    - name: Wait and check container status
-      run: |
-        sleep 10
-        STATUS=$(docker inspect --format='{{.State.Status}}' bngblaster-container)
-        echo "Container status: $STATUS"
-        if [ "$STATUS" = "running" ]; then
-          echo "Container is running!"
-        else
-          echo "Container is not running: $STATUS"
-          exit 1
-        fi
+    # - name: Wait and check container status
+    #   run: |
+    #     sleep 10
+    #     STATUS=$(docker inspect --format='{{.State.Status}}' bngblaster-container)
+    #     echo "Container status: $STATUS"
+    #     if [ "$STATUS" = "running" ]; then
+    #       echo "Container is running!"
+    #     else
+    #       echo "Container is not running: $STATUS"
+    #       exit 1
+    #     fi
 
     # - name: Run Robot Framework tests
     #   run: robot tests/
 
-    - name: Delete image if test fail
-      if: failure()
-      run: |
-        REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
-        echo "Repo name: $REPO_NAME"
-
-        VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-        "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" \
-        | jq -r '.[] | select(.metadata.container.tags[] == "v1.${{ github.RUN_NUMBER }}") | .id')
-
-        echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV
-        echo "Package version ID: $VERSION_ID"
-
-        curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
-
-    # - name: Delete GHCR image if test fails
+    # - name: Delete image if test fail
     #   if: failure()
-    #   uses: actions/delete-package-versions@v5
+    #   run: |
+    #     REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
+    #     echo "Repo name: $REPO_NAME"
+
+    #     VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+    #     "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" \
+    #     | jq -r '.[] | select(.metadata.container.tags[] == "v1.${{ github.run_number }}") | .id')
+
+    #     echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV
+    #     echo "Package version ID: $VERSION_ID"
+
+    #     curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+    #     -H "Accept: application/vnd.github.v3+json" \
+    #     "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
+
+
+    # - name: Tag latest image and push to GitHub Container Registry
+    #   if: success()
+    #   run: |
+    #     docker tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} ghcr.io/${{ env.REPO }}:latest
+    #     docker push ghcr.io/${{ env.REPO }}:latest
+
+    # - name: 'Upload robot test result'
+    #   if: always()
+    #   uses: actions/upload-artifact@v4.6.0
     #   with:
-    #     package-name: ${{ env.REPO }}
-    #     package-type: "container"
-    #     owner: ${{ github.repository_owner }}
-    #     token: ${{ secrets.GITHUB_TOKEN }}
-    #     package-version-ids: ${{ env.VERSION_ID }}
-
-    - name: Tag latest image and push to GitHub Container Registry
-      if: success()
-      run: |
-        docker tag ghcr.io/${{ env.REPO }}:v1.${{ github.run_number }} ghcr.io/${{ env.REPO }}:latest
-        docker push ghcr.io/${{ env.REPO }}:latest
-
-    - name: 'Upload robot test result'
-      if: always()
-      uses: actions/upload-artifact@v4.6.0
-      with:
-        name: robot-test-report
-        path: ./report.html
+    #     name: robot-test-report
+    #     path: ./report.html
 
   # update: 
   #   if: alway() ${{ github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job_name == 'update') }}
