fix: set condition for send mail

diff --git a/.github/workflows/scan_dockerfile_and_image.yml b/.github/workflows/scan_dockerfile_and_image.yml
--- a/.github/workflows/scan_dockerfile_and_image.yml
+++ b/.github/workflows/scan_dockerfile_and_image.yml
@@ -35,13 +35,16 @@ jobs:
       id: scan_dockerfile
       run: |  
         trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
-        if [[ $? 1 ]]; then
-          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_OUTPUT
+        if [[ $? -ne 0 ]]; then
+          echo "scanning_fail=true" >> $GITHUB_OUTPUT
         fi
       continue-on-error: true
       
+    - name: echo
+      run: echo "${{ steps.scan_dockerfile.outputs.scanning_fail }}"
+
     - name: Send mail to committer if detect vulnerability in Dockerfile
-      if: steps.scan_dockerfile.outputs.SCANNING_DOCKERFILE_FAILED == 'true'
+      if: steps.scan_dockerfile.outputs.scanning_fail == 'true'
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
