fix: set condition for send mail

diff --git a/.github/workflows/scan_dockerfile_and_image.yml b/.github/workflows/scan_dockerfile_and_image.yml
--- a/.github/workflows/scan_dockerfile_and_image.yml
+++ b/.github/workflows/scan_dockerfile_and_image.yml
@@ -35,18 +35,15 @@ jobs:
       id: scan_dockerfile
       run: |  
         trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
-        if [[ $? -ne 0 ]]; then
-          echo "scanning_fail=true" >> $GITHUB_OUTPUT
-        else 
-          echo "scanning_fail=false" >> $GITHUB_OUTPUT
-        fi
+        # if [[ $? -ne 0 ]]; then
+        #   echo "scanning_fail=true" >> $GITHUB_OUTPUT
+        # else 
+        #   echo "scanning_fail=false" >> $GITHUB_OUTPUT
+        # fi
       continue-on-error: true
-      
-    - name: echo
-      run: echo "${{ steps.scan_dockerfile.outputs.scanning_fail }}"
 
     - name: Send mail to committer if detect vulnerability in Dockerfile
-      if: steps.scan_dockerfile.outputs.scanning_fail == 'true'
+      if: failure()
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
@@ -74,7 +71,6 @@ jobs:
     - name: Show results for Dockerfile scanning
       run: |
         echo "##[command] Show results for Dockerfile scanning"
-        echo ${{ steps.scan_dockerfile.outputs.SCANNING_DOCKERFILE_FAILED }}
         cat dockerfile_scanning_result.json
   
     - name: Build image
