fix: set condition for send mail

diff --git a/.github/workflows/scan_dockerfile_and_image.yml b/.github/workflows/scan_dockerfile_and_image.yml
--- a/.github/workflows/scan_dockerfile_and_image.yml
+++ b/.github/workflows/scan_dockerfile_and_image.yml
@@ -34,16 +34,16 @@ jobs:
     - name: Scan Dockerfile 
       id: scan_dockerfile
       run: |  
-        trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
-        if [[ $? -ne 0 ]]; then
-          echo "scanning_fail=true" >> $GITHUB_ENV
-        else 
-          echo "scanning_fail=false" >> $GITHUB_ENV
-        fi
-      continue-on-error: true
+        # trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
+        # if [[ $? -ne 0 ]]; then
+          echo "scanning_fail=true" >> $GITHUB_OUTPUT
+        # else 
+        #   echo "scanning_fail=false" >> $GITHUB_OUTPUT
+        # fi
+      # continue-on-error: true
 
     - name: Echo scanning_fail
-      run: echo "${{ env.scanning_fail }}"
+      run: echo "${{ steps.scan_dockerfile.outputs.scanning_fail }}"
 
     - name: Send mail to committer if detect vulnerability in Dockerfile
       # if: steps.scan_dockerfile.outputs.scanning_fail == 'true'
