fix: set condition for send mail

diff --git a/.github/workflows/scan_dockerfile_and_image.yml b/.github/workflows/scan_dockerfile_and_image.yml
--- a/.github/workflows/scan_dockerfile_and_image.yml
+++ b/.github/workflows/scan_dockerfile_and_image.yml
@@ -35,8 +35,8 @@ jobs:
       id: scan_dockerfile
       run: |  
         trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
-        if [[ $? -ne 0 ]]; then
-          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_ENV
+        if [[ $? 1 ]]; then
+          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_OUTPUT
         fi
       continue-on-error: true
       
