fix: set condition for send mail

diff --git a/.github/workflows/scan_dockerfile_and_image.yml b/.github/workflows/scan_dockerfile_and_image.yml
--- a/.github/workflows/scan_dockerfile_and_image.yml
+++ b/.github/workflows/scan_dockerfile_and_image.yml
@@ -32,10 +32,16 @@ jobs:
       run: trivy version
   
     - name: Scan Dockerfile 
-      run: trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
-
+      id: scan_dockerfile
+      run: 
+        trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
+        if [[ $? -ne 0 ]]; then
+          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_OUTPUT
+        fi
+      continue-on-error: true
+      
     - name: Send mail to committer if detect vulnerability in Dockerfile
-      if: failure()
+      if: steps.scan_dockerfile.outputs.SCANNING_DOCKERFILE_FAILED == 'true'
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
@@ -59,9 +65,8 @@ jobs:
           SRE Team
         to: ${{ github.event.head_commit.author.email }}
         from: kien.kim@svtech.com.vn
-  
+
     - name: Show results for Dockerfile scanning
-      if: always()
       run: |
         echo "##[command] Show results for Dockerfile scanning"
         cat dockerfile_scanning_result.json
